// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

package org.example.worker;

public interface TaskResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.TaskResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 offset = 1;</code>
   * @return The offset.
   */
  long getOffset();

  /**
   * <code>string status = 2;</code>
   * @return The status.
   */
  String getStatus();
  /**
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
